modLoader= "javafml"
loaderVersion= "[52,)"
license= "mit"

[[mods]]
modId= "resptoken"
version= "1.2.0"
authors= "UltimatePorkerz"
description= '''Makes dying less stressful'''

[[dependencies.resptoken]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.resptoken]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.21.2)"
    ordering="NONE"
    side="BOTH"