modLoader= "javafml"
loaderVersion= "[45,)"
license= "mit"

[[mods]]
modId= "resptoken"
mod_version= "1.0.1"
authors= "UltimatePorkerz"
description= '''Makes dying less stressful'''

[[dependencies.resptoken]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resptoken]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resptoken]]
modId = "framework"
mandatory = true
versionRange = "[0.7,)"
ordering = "NONE"
side = "BOTH"