
#General Settings
[general]
	#Should debugging be enabled? (Default false)
	enableDebugging = true
	#Should players joining for the first time be given a respawn token? (default true)
	enableFirstTimeJoin = true
	#The amount of time it takes to teleport a player to their last death location when respawning. (Default 8)
	#Range: > 0
	teleportCountdown = 2
	#Should the player be invulnerable when teleporting back to their death location?
	invulnerabilityEnabled = true
	#How long the player is invulnerable for when teleporting back to their death location upon respawn. (default 16)
	#Range: > 0
	invulnerabilityCountdown = 16
	#If a player dies in lava, should it extend their invulnerability?
	lavaDeathExtendInvulnerability = true
	#How much should it extend it by? This will add on top of the currently set countdown. (default 60)
	#Range: > 0
	lavaDeathExtensionAmount = 60
	#Should death chests be enabled? This will save the players inventory in a chest upon death. (default true)
	enableDeathChest = true
	#Maximum durability for the respawn token. (-1 for infinite - Default 8)
	#Range: > -1
	tokenDurability = 8
	#Maximum durability for the Binding Glue. (-1 for infinite -  Default 8)
	#Range: > -1
	glueDurability = 8

